sudo:
  false

language:
  php

php:
  - 5.6

before_script:
  - composer install --dev --no-interaction --prefer-source
  - phpenv rehash

script:
  - phpunit --configuration test/phpunit.xml --coverage-clover=coverage.clover --testdox test/
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
