<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosApiClient\Api\Client'                 => __DIR__ . '/src/LosApiClient/Api/Client.php',
    'LosApiClient\Api\ClientFactory'          => __DIR__ . '/src/LosApiClient/Api/ClientFactory.php',
    'LosApiClient\Api\Response'               => __DIR__ . '/src/LosApiClient/Api/Response.php',
    'LosApiClient\Exception\RuntimeException' => __DIR__ . '/src/LosApiClient/Exception/RuntimeException.php',
    'LosApiClient\Module'                     => __DIR__ . '/src/LosApiClient/Module.php',
    'LosApiClient\Resource\Paginator'         => __DIR__ . '/src/LosApiClient/Resource/Paginator.php',
    'LosApiClient\Resource\Resource'          => __DIR__ . '/src/LosApiClient/Resource/Resource.php',
);
